version: '3.8'
services:
  phpmy:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
    links:
      - db
    environment:
      PMA_HOST: db
    networks:
      - backend
  db:
    image: mysql
    restart: always
    env_file:
      - .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql:/var/lib/mysql
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    networks:
      - backend
  node-app:
    image: node:14
    volumes:
      - .:/usr/src/service/
    working_dir: /usr/src/service/
    links:
      - db:db
    environment:
      - MYSQL_HOST=db
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - db
    command: bash -c "npm run dev"

  nginx:
    image: nginx
    ports:
      - 80:80
    links:
      - node-app:node-app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
      - backend
    depends_on:
      - node-app
volumes:
  mysql:


networks:
  backend:
    name: node-app-network
